title: "筑波大学 集中講義2025 by 福井徳朗"
description: "講義資料とサンプルコード"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
favicon: "/assets/images/favicon.ico"

feed: false
show_feed_links: false

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

sidebar:
  nav: "main"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "main"
      header:
        overlay_image: /assets/images/nuclfig.jpg
        overlay_filter: 0.5

custom_js:
  - "/Lecture_Tsukuba2025/assets/js/chatbot.js"
  - "/Lecture_Tsukuba2025/assets/js/custom.js"

custom_css:
  - /assets/css/custom.css
